sudo: false
language: node_js
node_js:
  - 6
  - 8
  - node
after_success:
  - npm run coverage
  - ./deploy.sh
env:
  global:
    - COMMIT_AUTHOR_EMAIL: whodunit@whodunit.io
    - COMMIT_AUTHOR_NAME: whodunit
    - SOURCE_BRANCH: master
    - TARGET_BRANCH: gh-pages
    - DOCS_DIR: ../whodunit-investigator-doc
    - GH_OWNER: whodunit
    - GH_PROJECT_NAME: investigator
    - DEPLOY_ON_NODE_VERSION: 6
    - secure: >-
        Hv7gACQoYGtesz1NTJYRHjGCimEJEjj4bQP2iTpDUUbfAiYe/4QPemoyDEFjRxbu5m2uoYwMk0AQrW7DnQhNAhl7u24jYnRgQyd/2GOx3xZgjwnao27gsrTHss4IyXEaS2h3kRuIVSD+xibz/lwZm+erHOQ9VOwvCQkOKnILXW8=
